spring.application.name=account-shop
# ===============================
# 1. CONNECT SQL SERVER
# ===============================
#sql server url
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShopAccountDB_V1;encrypt=true;trustServerCertificate=true;
#database username
spring.datasource.username=sa
#database password
spring.datasource.password=12345
# ===============================
# 2. CONFIG JPA / HIBERNATE
# ===============================
# create missing field or table
spring.jpa.hibernate.ddl-auto=update
# display SQL
spring.jpa.show-sql=true
# khong convert sang gach duoi 
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# ===============================
# 3. CONFIG JWT
# ===============================
#jwt config
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000